### ISSUE TITLE
Release 1.1.2 is not on releases

### ISSUE THREAD

**Issue by raimonkh** [react-native-webrtc/react-native-carrier-info#15]
Hello I'm updating the lib because I need it for RN 0.60.
I see the commit, and I see that the last commit says release 1.1.2.
But I can't see that on the releases section of github (says last is 1.1.2).
Is it possible that the tag was not added?

**Comment by raimonkh** [comment]
Seems like it's just "Drafting a new release" from Github UI

**Comment by zxcpoiu** [comment]
`1.1.2` has already published to npm. You can check versions using `npm show react-native-carrier-info versions`, which shows the latest versions is `1.1.2`. You can upgrade it with or without tags.

But you are right, the git tag `1.1.2` is not pushed to upstream. It has been there now. Thanks.

**Comment by raimonkh** [comment]
<3
